# Generated by Django 5.0.7 on 2024-08-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_goal_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalrating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
