# Generated by Django 5.0.7 on 2024-08-05 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_rename_ratings_goalrating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalAreaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_area_ratings', to=settings.AUTH_USER_MODEL)),
                ('functional_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='performance.functionalarea')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_area_raters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
